server:
  port: 8080

spring:
  application:
    name: care-connect-patient
  datasource:
    url: jdbc:mysql://localhost:3306/care_connect
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    server-url:
      default-zone=http://localhost:8761/eureka: